spring:
  main:
    banner-mode: "off"

  data:
    mongodb:
      host: localhost
      port: 27017

vs:
  email:
    host: in.mailjet.com
    port: 587
    userName: 8394886f02b223478a77157741f574b0
    password: 4c51ed05b195547506c69524b7ee6c27
    from: VantaShala
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
    mail.smtp.starttls.required: true
    mail.smtp.debug: true
