spring:
  main:
    banner-mode: "on"

  data:
    mongodb:
      host: localhost
      port: 27017

vs:
  email:
    host: smtp.gmail.com
    port: 587
    userName: alertsoalerts
    password: gopikrishna

