spring:
  profiles.active: dev

  velocity:
    cache: true
    resource-loader-path : classpath:/config/vm/

  jersey:
    application-path: /rest # Path that serves as the base URI for the application. Overrides the value of "@ApplicationPath" if specified.
    filter.order: 0 # Jersey filter chain order.
    type: servlet # Jersey integration type. Can be either "servlet" or "filter".
    init.*:

  data:
    mongodb:
      database: VantaShala
      repositories.enabled: true

  social:

    facebook:
      app-id: 1144441838907025
      app-secret: 5efeb88dbcd8d94bdd576ca3990c657f

    twitter:
      app-id: 3MeOLDqCHWBbxIhDPX5OknIYM
      app-secret: NVN3NmGaobsravXkcPe5CpDnwHOUifdKLggHAjb0NipkG6efwB

    google:
       app-id: 757001337265-7v4coh9fdfpu0dpbnd4pmjsr7a32lloj.apps.googleusercontent.com
       app-secret: KvjbI-SXVKZWIKyUB4Aik1-9


server:
  context-path: /vs

vs:
  mongo:
    repos:
      userCollectionName: user
      roleCollectionName: role
      orderStatusCollectionName: orderStatus
      menuStatusCollectionName: menuStatus
      emailStatusCollectionName: emailStatus
      emailCollectionName: emails
  uploads:
    location: /fileUploads/
  email:
    from: VantaShala
    fromOrderEmail: order@VantaShala.com
    fromSupportEmail: support@VantaShala.com
    fromContactEmail: contact@VantaShala.com
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
    mail.smtp.starttls.required: true
    mail.smtp.debug: true

 # server.servlet-path=/some_context_for_spring_mvc