spring:
  profiles.active: dev

  velocity:
    cache: true
    resource-loader-path : classpath:/config/vm/

  jersey:
    application-path: /rest # Path that serves as the base URI for the application. Overrides the value of "@ApplicationPath" if specified.
    filter.order: 0 # Jersey filter chain order.
    type: servlet # Jersey integration type. Can be either "servlet" or "filter".
    init.*:

  data:
    mongodb:
      database: VantaShala
      repositories.enabled: true

server:
  context-path: /vs

vs:
  mongo:
    repos:
      userCollectionName: user
      roleCollectionName: role
      orderStatusCollectionName: orderStatus
      menuStatusCollectionName: menuStatus
      menuStatusCollectionName: emailStatus
      emailCollectionName: emails
  uploads:
    location: /fileUploads/
  email:
    from: VantaShala
    fromOrderEmail: order@VantaShala.com
    fromSupportEmail: support@VantaShala.com
    fromContactEmail: contact@VantaShala.com
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
    mail.smtp.starttls.required: true
    mail.smtp.debug: true
 # server.servlet-path=/some_context_for_spring_mvc