spring:
  profiles.active: dev

  velocity:
    cache: true
    resource-loader-path : classpath:/config/vm/

  jersey:
    application-path: /rest # Path that serves as the base URI for the application. Overrides the value of "@ApplicationPath" if specified.
    filter.order: 0 # Jersey filter chain order.
    type: servlet # Jersey integration type. Can be either "servlet" or "filter".
    init.*: 
server:
  context-path: /vs

 # server.servlet-path=/some_context_for_spring_mvc